[package]
name = "c16b64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = "0.2.0"
llvm-sys = "160.1.2"
